name: Build

on:
  push:
    branches: 
      - main
    # tags:
    #   - '*'
  pull_request:
    branches: 
      - main

env:
  REPO_OWNER_LOWER: ${{ github.repository_owner }}
  IMAGE_NAME: uptime-service-backend-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: üì• Checkout
      uses: actions/checkout@v4

    - name: üì• Update Git Submodules
      run: |
        git submodule init
        git submodule update

    - name: üì¶ Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: üõ†Ô∏è Build
      run: nix-shell --run "make build"

    - name: üõ†Ô∏è Build Docker
      env:
        TAG: latest
      run: nix-shell --run "make docker"

    - name: üß™ Test
      run: nix-shell --run "make test"

    - name: üîë Log in to Container Registry
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: üè∑Ô∏è Extract branch name
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Repo owner lowercase
      run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: üè∑Ô∏è Tag and Push Docker Image (main branch)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Tag the existing image for GHCR
        docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:latest
        docker tag ${{ env.IMAGE_NAME }} ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ github.sha }}
        # Push to GHCR
        docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:latest
        docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ github.sha }}

    - name: üè∑Ô∏è Tag and Push Docker Image (pull request)
      if: github.event_name == 'pull_request'
      run: |
        # Tag the existing image for GHCR with branch name
        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ steps.extract_branch.outputs.branch }}
        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ github.sha }}
        # Push to GHCR
        docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ steps.extract_branch.outputs.branch }}
        docker push ghcr.io/${{ env.REPO_OWNER_LOWER }}/uptime-service-backend:${{ github.sha }}
