name: Integration

on:
  push:
    branches:
      - main
    # tags:
    #   - '*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  REPO_OWNER_LOWER: ${{ github.repository_owner }}
  IMAGE_NAME: uptime-service-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ðŸ“¥ Checkout
      uses: actions/checkout@v4

    - name: ðŸ“¥ Update Git Submodules
      run: |
        git submodule init
        git submodule update

    - name: ðŸ“¦ Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: ðŸ¤Œ Get Minimina
      uses: MinaFoundation/install-minimina-action@v1
      with:
        stream: stable
        # commit_or_branch: resource-experiments

    - name: ðŸ› ï¸ Build Docker
      env:
        TAG: integration-test
      run: nix-shell --run "make docker"

    - name: ðŸ§ª Run Integration Tests
      env:
        # UPTIME_SERVICE_SECRET is a passphrase needed to decrypt uptime service config files
        UPTIME_SERVICE_SECRET: ${{ secrets.UPTIME_SERVICE_SECRET }}
      run: nix-shell --run "make integration-test"
      timeout-minutes: 30

    - name: ðŸ“– Get logs
      if: always()
      run: |
        mkdir -p integration-test/logs
        minimina network list
        minimina network status -n integration-test
        minimina node logs -n integration-test -i uptime-service-backend -r > integration-test/logs/uptime-service-backend.log
        minimina node logs -n integration-test -i node-a -r > integration-test/logs/node-a.log
        minimina node logs -n integration-test -i node-b -r > integration-test/logs/node-b.log

    - name: ðŸ“Ž Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: logs
        path: integration-test/logs
